# Copyright Benedek Thaler 2015-2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
sudo: false

branches:
  only:
    - master

env:
  matrix:
    # Workaround for: https://github.com/travis-ci/travis-ci/issues/4681
    - TRAVIS_EXTRA_JOB_WORKAROUND=true

matrix:
  include:

    # GCC 4.8
    - env: CXX=g++-4.8 CXX_PATH=/usr/bin/g++-4.8 CXX_NAME=gcc VARIANT=sanitize ARCH=64
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    # GCC 5.3
    - env: CXX=g++-5 CXX_PATH=/usr/bin/g++-5 CXX_NAME=gcc VARIANT=sanitize ARCH=64
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    # GCC 5.3 -- 32 bit
    - env: CXX=g++-5 CXX_PATH=/usr/bin/g++-5 CXX_NAME=gcc VARIANT=sanitize ARCH=32
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-5-multilib

    # Disabled because of: https://github.com/travis-ci/travis-ci/issues/5624
    # Clang 3.5
    #- env: CXX=clang++-3.5 CXX_PATH=/usr/bin/clang++-3.5 CXX_NAME=clang VARIANT=release
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test # depends on libstdc++
    #        - llvm-toolchain-precise-3.5
    #      packages:
    #        - clang-3.5

    # Clang 3.7
    - env: CXX=clang++-3.7 CXX_PATH=/usr/bin/clang++-3.7 CXX_NAME=clang VARIANT=release ARCH=64
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test # depends on libstdc++
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7

    # Xcode 6.4
    - env: CXX=clang++ CXX_PATH=clang++ CXX_NAME=clang VARIANT=release ARCH=64
      os: osx
      osx_image: xcode6.4

  exclude:
    - env: TRAVIS_EXTRA_JOB_WORKAROUND=true

install:
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

    # Install Boost
    BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz"
    mkdir boost && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost
    export BOOST_ROOT=${DEPS_DIR}/boost
    export BOOST_BUILD_PATH=${BOOST_ROOT}

    # Setup Boost.Build
    echo "using ${CXX_NAME} : : ${CXX_PATH} ;" > ${HOME}/user-config.jam
    cd ${BOOST_ROOT}
    ./bootstrap.sh --with-libraries=serialization # build b2
    ./b2 toolset=${CXX_NAME} address-model=${ARCH} -j4  # build libraries
    export PATH=${BOOST_ROOT}:${PATH}

    cd ${TRAVIS_BUILD_DIR}

script:
  - |
    cd test
    b2 toolset=${CXX_NAME} variant=${VARIANT} address-model=${ARCH} -j2

