# Copyright Benedek Thaler 2015-2016
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

branches:
  only:
    - master

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_BUILD_PATH: C:\Libraries\boost_1_60_0

install:
  - cd  C:\Libraries\boost_1_60_0
  - call .\bootstrap.bat
  - call .\b2 --with-serialization
  - xcopy stage\lib\libboost_serialization-vc*-mt-gd-1_*.lib stage\lib\boost_serialization.lib*

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - dir C:\Libraries\boost_1_60_0 C:\Libraries\boost_1_60_0\stage\lib

build_script:
  - cd C:\projects\double-ended\test
  - call C:\Libraries\boost_1_60_0\b2.exe toolset=msvc
